# -*- coding: utf-8 -*-
"""interface.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SASp312iTXGBGvi9v137TJDOUC-gHKei
"""

import streamlit as st
import pandas as pd
from io import BytesIO
from traitement_f13 import code_traitement_F13
from traitement_machines import code_traitement_machines

st.set_page_config(page_title="Classement Machines", layout="centered")

st.title("📊 Classement des données machines")
st.write("Uploadez les fichiers ci-dessous pour générer le rapport.")

st.sidebar.title("📘 Mode d'emploi")
st.sidebar.markdown("""
1. Cliquer sur "Browse files" pour télécharger le fichier à traiter

⚠️ Il faut que le fichier s'appelle "Business Unit Groupe 2.xlsx"

2. Cliquer sur "🧪 Lancer le traitement F13" ou "🧪 Lancer le traitement machines" pour traiter en fonction du F13 seulement ou de tous les types d'arrêts

3. Cliquer sur "📥 Télécharger le fichier classé" pour l'enregistrer sur votre appareil.

⚠️ Cet outil n'enregistre pas les fichiers (il faut bien importer à chaque fois)

""")

st.sidebar.image("logo.png", width=500)

# Téléversement du fichier principal
uploaded_file = st.file_uploader("📁 Fichier 'Business Unit Groupe 2.xlsx'", type=["xlsx"])


if uploaded_file:
    if st.button("🧪 Lancer le traitement F13"):
        with st.spinner("Traitement en cours..."):

            fichier_F13 = code_traitement_F13(uploaded_file)

            st.success("✅ Traitement terminé !")
            st.download_button(
                label="📥 Télécharger le fichier classé",
                data=fichier_F13.getvalue(),
                file_name="Impact_F13.xlsx",
                mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
            )
    if st.button("🧪 Lancer le traitement machines"):
        with st.spinner("Traitement en cours..."):

            fichier_machines = code_traitement_machines(uploaded_file)

            st.success("✅ Traitement terminé !")
            st.download_button(
                label="📥 Télécharger le fichier classé",
                data=fichier_machines.getvalue(),
                file_name="Impact_machines.xlsx",
                mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
            )
else:
    st.info("Veuillez téléverser le fichier pour commencer.")