# -*- coding: utf-8 -*-
"""interface.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SASp312iTXGBGvi9v137TJDOUC-gHKei
"""

import streamlit as st
import pandas as pd
from io import BytesIO
from traitement import traiter_fichier_excel  # Ton code existant ici

st.set_page_config(page_title="Classement Machines", layout="centered")

st.title("📊 Classement des données machines")
st.write("Uploadez les fichiers ci-dessous pour générer le rapport.")

# Téléversement du fichier principal
uploaded_file = st.file_uploader("📁 Fichier 'Business Unit Groupe 2.xlsx'", type=["xlsx"])


if uploaded_file:
    if st.button("🧪 Lancer le traitement"):
        with st.spinner("Traitement en cours..."):

            fichier_sortie = traiter_fichier_excel(uploaded_file)

            st.success("✅ Traitement terminé !")
            st.download_button(
                label="📥 Télécharger le fichier classé",
                data=fichier_sortie.getvalue(),
                file_name="Impact_F13.xlsx",
                mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
            )
else:
    st.info("Veuillez téléverser les deux fichiers pour commencer.")