# -*- coding: utf-8 -*-
"""traitement_F13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zFlWwa1yI9nsuYRUz9T2EzRAV3lGjaK3
"""

def code_traitement_F13(fichier_données):
    import pandas as pd
    import matplotlib.pyplot as plt
    from openpyxl import Workbook
    from openpyxl.utils import get_column_letter
    from openpyxl.drawing.image import Image as ExcelImage
    from openpyxl import load_workbook
    from io import BytesIO

    # 1. Chargement des données
    données = pd.read_excel(fichier_données, sheet_name="COMMENTAIRES")
    causes = pd.read_excel("GR2.xlsx", sheet_name="Sheet1")

    if données.columns[0] == "COMMENTAIRES" :
        données = pd.read_excel(fichier_données, sheet_name="COMMENTAIRES", skiprows=2)

    données = données.rename(columns={
        "05_Date Heure Début": "Date Heure Début",
        "09_Cause MatUnitaire": "Cause MatUnitaire",
        "07_CodeOAQ10": "Code",
        "70_Commentaires": "Commentaires",
        "20_Durée (mn)": "Durée (mn)"
    })

    données = données[données['Code'].isin(['F13A', 'F13B', 'F13C'])]
    données['Cause MatUnitaire'] = données['Cause MatUnitaire'].astype(str)
    causes['Cause'] = causes['Cause'].astype(str)
    données['Durée (mn)'] = données['Durée (mn)'].round(0).astype(int)

    # Fonctions d’extraction
    def extraire_machine(code):
        if code != "-":
            dico = str(code).split('.')
            if len(dico) > 1:
                return dico[0] if dico[0] == "ZA" else dico[2]

    def extraire_sous_code(code):
        if code != "-":
            dico = str(code).split('.')
            if len(dico) > 2 and dico[2] != "00":
                return dico[0] if dico[0] == "ZA" else dico[3]

    def extraire_cause(code):
        dico = str(code).split('.')
        if len(dico) > 1:
            if dico[0] == "ZA":
                return "Non renseigné"
            if dico[2] != "00":
                return f"{dico[2]}.{dico[3]}"

    données['Machine'] = données['Cause MatUnitaire'].apply(extraire_machine)
    données['Sous-code'] = données['Cause MatUnitaire'].apply(extraire_sous_code)
    causes['Causes'] = causes['Cause'].apply(extraire_cause)
    données['Causes'] = données['Cause MatUnitaire'].apply(extraire_cause)

    données = données[données['Machine'].notna() & données['Sous-code'].notna() & données['Causes'].notna()]
    causes = causes[causes['Causes'].notna()]
    données = données.merge(causes[['Causes', 'Description']], on='Causes', how='left')
    données['Description'] = données['Description'].fillna("Non renseigné")

    # Résumé par machine
    durée_tot = données.groupby('Machine')['Durée (mn)'].sum().reset_index()
    durée_tot = durée_tot.sort_values(by='Durée (mn)', ascending=False)
    durée_tot['Durée (mn)'] = durée_tot['Durée (mn)'].round(0).astype(int)

    dico_machines = {machine: données[données['Machine'] == machine] for machine in données['Machine'].unique()}
    machines_triées = durée_tot['Machine'].tolist()

    # Création du fichier en mémoire
    output = BytesIO()
    with pd.ExcelWriter(output, engine='openpyxl') as writer:
        données.to_excel(writer, sheet_name="Données", index=False)
        durée_tot.to_excel(writer, sheet_name="Machines", index=False)

        for clé_machine in machines_triées:
            if clé_machine == "00":
                continue
            val_machine = dico_machines.get(clé_machine)
            résumé = val_machine.groupby(['Sous-code', 'Description'])['Durée (mn)'].sum().reset_index()
            résumé = résumé.rename(columns={'Durée (mn)': 'Durée totale (mn)'})
            résumé = résumé.sort_values(by='Durée totale (mn)', ascending=False)
            résumé['Durée totale (mn)'] = résumé['Durée totale (mn)'].round(0).astype(int)
            résumé.to_excel(writer, sheet_name=clé_machine, index=False)

            # On charge le classeur pour ajouter les graphiques dans les bonnes feuilles
            wb = load_workbook(filename=output)
            ws = wb["clé_machine"]

            # --- Graphique : Résumé sous-codes machine ---
            fig = plt.figure(figsize=(10, 6))
            plt.bar(résumé["Sous-code"], résumé["Durée totale (mn)"], color='skyblue')
            plt.title("Temps d'arrêt total par cause")
            plt.xlabel("Machine")
            plt.ylabel("Durée d'arrêt (min)")
            plt.xticks(rotation=45, ha='right')
            plt.tight_layout()

            img_buffer = BytesIO()
            fig.savefig(img_buffer, format='png')
            plt.close(fig)
            img_buffer.seek(0)

            # --- Ajout dans le fichier Excel ---
            img = ExcelImage(img_buffer)
            img.anchor = 'H5'
            ws.add_image(img)

            # --- Réenregistrement du fichier Excel en mémoire ---
            output = BytesIO()
            wb.save(output)
            output.seek(0)


        # Création de la feuille avec classement des sous-codes
        données['Machine.Sous-code'] = données['Machine'] + '.' + données['Sous-code']
        classement_sous_codes = (
            données.groupby(['Machine.Sous-code', 'Description'])['Durée (mn)']
            .sum()
            .reset_index()
            .rename(columns={'Durée (mn)': 'Durée totale (mn)'})
            .sort_values(by='Durée totale (mn)', ascending=False)
        )
        classement_sous_codes['Durée totale (mn)'] = classement_sous_codes['Durée totale (mn)'].round(0).astype(int)

        classement_sous_codes.to_excel(writer, sheet_name="Classement Sous-codes", index=False)

        # Ajustement des colonnes
        workbook = writer.book
        for ws in workbook.worksheets:
            for col in ws.columns:
                max_length = 0
                col_letter = get_column_letter(col[0].column)
                for cell in col:
                    if cell.value:
                        max_length = max(max_length, len(str(cell.value)))
                ws.column_dimensions[col_letter].width = max_length + 2

    output.seek(0)

    # On charge le classeur pour ajouter les graphiques dans les bonnes feuilles
    wb = load_workbook(filename=output)
    ws1 = wb["Machines"]
    ws2 = wb["Classement Sous-codes"]

    top_30 = classement_sous_codes.head(30)

    # --- Graphique 1 : Durée par machine ---
    fig1 = plt.figure(figsize=(10, 6))
    plt.bar(durée_tot["Machine"], durée_tot["Durée (mn)"], color='skyblue')
    plt.title("Temps d'arrêt total par machine")
    plt.xlabel("Machine")
    plt.ylabel("Durée d'arrêt (min)")
    plt.xticks(rotation=45, ha='right')
    plt.tight_layout()

    img_buffer1 = BytesIO()
    fig1.savefig(img_buffer1, format='png')
    plt.close(fig1)
    img_buffer1.seek(0)

    # --- Graphique 2 : Classement des causes ---
    fig2 = plt.figure(figsize=(10, 6))
    plt.bar(top_30["Machine.Sous-code"], top_30["Durée totale (mn)"], color='skyblue')
    plt.title("Classement général des causes")
    plt.xlabel("Cause")
    plt.ylabel("Durée d'arrêt (min)")
    plt.xticks(rotation=45, ha='right')
    plt.tight_layout()

    img_buffer2 = BytesIO()
    fig2.savefig(img_buffer2, format='png')
    plt.close(fig2)


    # --- Ajout dans le fichier Excel ---
    img1 = ExcelImage(img_buffer1)
    img1.anchor = 'H5'
    ws1.add_image(img1)

    img2 = ExcelImage(img_buffer2)
    img2.anchor = 'H5'
    ws2.add_image(img2)

    # --- Réenregistrement du fichier Excel en mémoire ---
    final_output = BytesIO()
    wb.save(final_output)
    final_output.seek(0)

    return final_output